#!/bin/sh

is_network_up() {
    ping -c1 -W1 8.8.8.8 >/dev/null 2>&1
}

is_time_valid() {
    # Year must be greater than 2020 for TLS to be happy
    CURRENT_YEAR=$(date +%Y)
    [ "$CURRENT_YEAR" -ge 2021 ]
}

start() {
        echo "Waiting for network to be ready..."
        RETRIES=10
        while ! is_network_up && [ $RETRIES -gt 0 ]; do
                sleep 1
                RETRIES=$((RETRIES - 1))
        done

        echo "Waiting for valid system time..."
        RETRIES=10
        while ! is_time_valid && [ $RETRIES -gt 0 ]; do
                sleep 1
                RETRIES=$((RETRIES - 1))
        done

        echo -n "Starting COG: "
        /usr/bin/cog http://lightningjs.io/fracer/ &> /dev/null &
}

stop() {
       	echo -n "Stopping COG: "
	killall cog WPEWebProcess WPENetworkProcess &> /dev/null
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
